"""
This program solves and then submits sudoku puzzles generated by sudoku.com
"""

import requests, numpy as np
from bs4 import BeautifulSoup

def main():
    response = requests.get('https://sudoku.com', timeout=10)
    print(response.text)
    #data = response.json()
    #print(data)

    #soup = BeautifulSoup(response.text, parse_only=True)
    #print(soup.prettify())
    pass









if __name__ == '__main__':
    main()
    pass
